- README.md
- contributing.md
- packages/nx-playwright/package.json
<sup>(What is this PR for?)</sup>
- [Contributing guidelines](https://github.com/marksandspencer/nx-plugins/contributing.md)
> Added some extra details to readme

- .github/workflows/pr.yml
- package.json
[PR checks doesn't run on forked branches](https://github.com/marksandspencer/nx-plugins/pull/22#issuecomment-1219313170)
Switching to a shallow checkout
> Fixing build by switching to a shallow checkout

- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
- packages/nx-playwright/src/generators/project/root-config/playwright.config.base.ts__tmpl__
The CLI Args were ignored
This uses a few of them,  and changes headed/browser to align with both the cypress plugin and the playwright cli
> Tweak cli args

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- Badges added to easily access links
- Bumped correct version of package
> Bump package.json 3

- CONTRIBUTING.md
Docs updated to bump the version in package.json 
> note added to bump version in package.json

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/project/files/playwright.config.ts__tmpl__
- packages/nx-playwright/src/generators/project/files/tsconfig.e2e.json
- packages/nx-playwright/src/generators/project/generator.spec.ts
- packages/nx-playwright/src/generators/project/generator.ts
There are a few small issues with the config and generator in the `nx-playwright` package.
Apply the fixes
N/A
> Fix issues with config and generator

- package.json
- packages/nx-playwright/package.json
Bump package versions – forgot to in previous PR.
As above
> Bump package versions

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
<sup>(What is this PR for?)</sup>
- readme debug flag missing
- update readme with debug flag
> chore: update readme with debug flag

- package.json
- packages/nx-playwright/package.json
- yarn.lock
Playwright is installed as a dependency of this monorepo but not required
Remove playwright dependency from top level package
> Remove playwright dependency from top level package

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/lib/start-dev-server.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/lib/start-dev-server.ts
- packages/nx-playwright/src/generators/project/generator.spec.ts
- packages/nx-playwright/src/generators/project/generator.ts
Fixes https://github.com/marksandspencer/nx-plugins/issues/58
<sup>Remove hostname from app serve executor</sup>
> nx-plugins-58 - fix hostname issue

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/project/files/src/smoketest.spec.ts__tmpl__
Smoke tests are specific to M&S setup.
Remove smoke tests.
> remove smoke tests

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
Add pass marker to playwright executor
> Add playwright marker to detect test pass

- local-test.sh
- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
<sup>Fixes #72 </sup>
Simplify executor and remove unnecessary code
Refactor input `proj` to `testProject`
> Simplify playwright executor

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
<sup>Fixes #78 </sup>
Re-add package runner as optional argument
> make package runner optional

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
`debug` option is missing from inputs
Add `debug` option
> Add debug option

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
Add ability to update snapshots for Playwright
Add --update-snapshots option
> Add update snapshots option

- .github/workflows/release.yml
<sup>https://github.com/marksandspencer/nx-plugins/issues/38</sup>
<sup>Update release to use correct pnpm command</sup>
> Fix pnpm release

- packages/nx-playwright/package.json
<sup>Playwright is out of date</sup>
<sup>Update Playwright</sup>
> Upgrade playwright

- .github/workflows/js/check-jobs-for-errors.js
- .github/workflows/pr.yml
- ci/version-check.ts
- package.json
- packages/nx-playwright/package.json
- pnpm-lock.yaml
<sup>Version check was broken due a previous change but pr validation did not fail</sup>
<sup>Fix version checks</sup>
This PR also includes pipeline improvements so that jobs can be run in parallel
> Fix version checks, improve PR pipelines

- .github/workflows/release.yml
- package.json
<sup>Release workflow is failing</sup>
<sup>Remove SAML token on checkout and use what pr.yml is using</sup>
> Fix checkout on release action

- package.json
- packages/nx-playwright/package.json
<sup>(What is this PR for?)</sup>
> Bump version

- .github/workflows/release.yml
- package.json
- packages/nx-playwright/package.json
checkout fails on the release workflow 
remove the saml token
> chore: remove saml github token

- .github/workflows/release.yml
- package.json
- packages/nx-playwright/package.json
Previous releases have failed due to expired npm token.
Trigger a new release to confirm release process works with new npm token.
> Trigger new release
