- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/project/generator.spec.ts
- packages/nx-playwright/src/generators/project/generator.ts
When using the `@mands/nx-playwright` generator, the generated `project.json` file does not contain a `ts-check` target.
Add a `ts-check` target to the generated `project.json` file.
> Add 'ts-check' target to generated project.json in nx-playwright

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
Needs timeout parameter and cleanup of flags
Adds `getFlags`function (to isolate how flags are assembled), and timeout parameter.
The rest of the non-implemented parameters are not in the stock cli and possibly should be removed from the .d.ts file.
Also got around to documenting the flags in the README :).
> Add additional parameters

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/project/generator.spec.ts
- packages/nx-playwright/src/generators/project/generator.ts
Generated e2e project has incorrect reference to TS config
Fix reference to ts config for generated e2e project
> Fix reference to ts config for generated e2e project

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
This allows using nx-playwright with different package managers
(yarn, npm, or pnpm).
Previously the package was hard-coded to use yarn as the runner, so it couldn't be used in projects that used npm/pnpm.
`runner` added as an option, defaulting to yarn to avoid breaking existing consumers.
> Add runner option to playwright

- packages/nx-playwright/README.md
`pnpn` instead of `pnpm` in root README.
Fix, and wrap in backticks.
> Fix minor typo in README

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
There was no support for options like grep and grep-invert.
Added options to support grep and grep-invert.
> Support grep and grepInvert options

- .vscode/extensions.json
- .vscode/settings.json
- package.json
- packages/nx-playwright/package.json
Playwright dependencies are not a peer dependencies  
Adding `@playwright/test` as a peer dependency to ensure that this plugin works and install correct (and tested) versions
> Adding @playwright/test as a peer dependency

- packages/nx-playwright/src/generators/project/files/src/smoketest.spec.ts__tmpl__
Every app (including new apps) now need at least 1 smoketest (tagged with `@smoketest`).
Added a dummy smoketest template for new apps.
N/A
> Add dummy smoketest template

- CONTRIBUTING.md
- package.json
- packages/nx-playwright/package.json
nx-playwright peerDependency on playwright 1.26.0 is restricted to that single version
Make it accept higher minor versions
> Basket-192: Make nx-playwright peerDependency on playwright more forgiving

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
Some apps may need to pass with no tests when grep or grep inverted are used.
Add an optional param `passWithNoTests` to allow for pass with no tests.
> allow optional pass with no tests

- package.json
- packages/nx-playwright/package.json
When installing storybook along with this nx-plugin we need to have matching versions of the playwright dependencies. The versions in this package are outdated.
Update packages `@playwright/test` and `playwright` to latest version
> Update playwright dependencies

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
- packages/nx-playwright/src/generators/project/files/tsconfig.e2e.json
Want to be able to customise the path the playwright tests run at
For BASKET-253
- Add path to executor options
- Switch tsconfig `include` from `src/**/*.ts` => `**/*.ts`, to match all files, not just src
> Add `path` option to executor

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
Want to be able to support the playwright `config` option.
- Add `config` to executor options
> Add `config` option to executor

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
When tests fail, logs are hard to read.  For example:
- Log `error.stdout` instead of entire error:
> Display failure logs in more readable format

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
I want to be able to use Playwright's projects feature, but the `--project` option is being swallowed by nx, ie. running
```
nx e2e demo-e2e --project=smth
```
results in NX error: 
```
Cannot find project 'smth'
```
and the playwright executor is not even reached.
Related to #63 .
Initially I wanted to fix this on NX level, by allowing `--project` flag to be passed to executors, but this would result in an unpredictable behavior and conflict with nx project feature itself.
So I propose to have `--proj` option in this library level to avoid any conflicts.
> Add support for --project option via --proj to not conflict with nx.

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
<sup>(What is this PR for?)</sup>
The new preview `--ui` CLI option is missing.
This pull request add the `--ui`CLI option added with 1.32: https://playwright.dev/docs/release-notes#version-132
> feat: add ui mode option

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/executors/playwright-executor/executor.spec.ts
- packages/nx-playwright/src/executors/playwright-executor/executor.ts
- packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts
- packages/nx-playwright/src/executors/playwright-executor/schema.json
Shard is an option in playwright that allows to run section of test on a given worker.
Extend code to support that option.
- [playwright docs](https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines)
> feat: added shard support

- package.json
- packages/nx-playwright/README.md
- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/init/generator.spec.ts
- packages/nx-playwright/src/generators/init/generator.ts
- packages/nx-playwright/src/generators/init/schema.d.ts
- packages/nx-playwright/src/generators/project/axe-files/axe-tests/axe-tests.spec.ts__tmpl__
- packages/nx-playwright/src/generators/project/axe-files/axe.config.ts__tmpl__
- packages/nx-playwright/src/generators/project/generator.spec.ts
- packages/nx-playwright/src/generators/project/generator.ts
- packages/nx-playwright/src/generators/project/schema-types.d.ts
- packages/nx-playwright/src/versions.ts
This PR adds the ability to generate AXE (accessibility) tests when running the `nx-playwright` generator.
`--includeAxe` flag can be included when running the generator:
```bash
pnpm nx generate @mands/nx-playwright:project <APP-NAME>-e2e --project <APP-NAME> --includeAxe
```
This will result in:
- addition of an `axe` configuration to `e2e` target in `project.json`
- generation of `apps/<APP-NAME>-e2e/axe.config.ts`: where URL paths can be added to be tested for accessibility issues
- generation of `apps/<APP-NAME>-e2e/axe-tests/axe-tests.spec.ts`: where the AXE tests are defined
- addition of `axe-playwright` as a devDependency
> Add --includeAxe flag to nx-playwright generator

- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/project/axe-files/axe-tests/axe-tests.spec.ts__tmpl__
- packages/nx-playwright/src/generators/project/generator.spec.ts
- packages/nx-playwright/src/generators/project/lib/add-linting.ts
When running the generator with the `--includeAxe` flag there are two linting issues being introduced:
- Imports are not following the standard proposed by [eslint-plugin-simple-import-sort](https://www.npmjs.com/package/eslint-plugin-simple-import-sort)
- AXE tests don't need an `expect` statement but not including any is prompted as a warning
- Template for AXE tests updated to follow standard import linting rules
- Added `"jest/expect-expect": "off"` override to the generated `.eslintrc.json` file when the `includeAxe` flag is present
> Fix: linting errors introduced in AXE tests

- .github/actions/prepare/action.yml
- .github/workflows/pr.yml
- package.json
- packages/nx-playwright/package.json
- packages/nx-playwright/src/generators/init/generator.spec.ts
- packages/nx-playwright/src/generators/init/generator.ts
- packages/nx-playwright/src/generators/project/generator.ts
- packages/nx-playwright/src/generators/project/lib/add-linting.ts
In Nx 17 `runTasksInSerial` is no longer exported from `@nx/workspace` and instead it must be imported from `@nx/devkit`.
There is also an issue with `addDependenciesToPackageJson` that arises when a project using Nx 17 omits the `--includeAxe` flag when calling the `nx-playwright` generator. Looks like the `undefined` value is no longer supported.
- All `runTasksInSerial` imports now come from `@nx/devkit`
- `addDependenciesToPackageJson` call refactored so the `axe-playwright` is omitted instead of  set to `undefined` when `--includeAxe` flag is missing
-  Bumped `pnpm` to `>= 8.9` in the engines section because CI was picking `Node v20` and `pnpm v7.x.x` which resulted in a failed `prepare` step
- Added `--e2eTestRunner=playwright` and  `--nextAppDir=false` flags to the "Test plugin" …
> Fixed issues with Nx 17

- .github/actions/get-node-version/action.yml
- .github/actions/prepare/action.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- package.json
- packages/nx-playwright/package.json
Trying to fix the issue where releasing a new version fails.
- release workflow:
- added permissions
- added `NODE_AUTH_TOKEN` env var
- tidied up scripting
- did some other tidying up
> Add use of NODE_AUTH_TOKEN when releasing
